pages/groups/_groupId/index.vue
pages/groups/index.vue

- Stream動画を埋め込む
- Streamサイトへのリンクを貼る
- 公演一覧を表示する
- 大きなウィンドウサイズの場合に2段組にする
- タグの表示
- SNSアカウントを表示する
- 整理券の表示
- 公演名（第○公演），時間
　　- 取得できない整理券はdisabled
- 取得できない場合は，①売り切れ②同時間帯の整理券を取得済　の最低2パターン
- 空席情報は「🟣🔺❌」で表示
- 整理券を取得できるようにする
（dataの中のプロパティ名"dialog"をそのまま使うと，整理券取得の際に複数のモーダルウィンドウが同時に出現するので，プロパティ名を"event_1"のように，各公演ごとに設定する必要がある点に注意）
- 埋め込みの仕様上，モーダルウィンドウを閉じてもStreamの再生が続く問題を解決する
- 写真（サムネイル）を表示する
- timetable_nameを取得し，公演名として表示する（axiosを使ったデータ取得から書かなきゃいけない）

40 各グループ個別ページのレイアウト整える in pages/groups/_groupId/index.vue

---

pages/groups/_groupId/index.vue

整理券取得画面のUIを改善．
- 利用者がスムーズに整理券を取得できるようにするため．
1. 各団体の整理券取得画面において，v-cardの高さを調整
2. 取得できない整理券（時間外＆完売）のv-cardをdisabledに
3. 不要な情報（特に配布時間）を非表示
4.  各団体個別ページのボタン位置（いいね，「映像で鑑賞」，映像鑑賞画面のclose）を変更
1. ページ先頭
2. 整理券選択画面
3. 整理券取得時のダイアログ
4. 映像鑑賞ページ

/groups/_groupId内の整理券取得画面UIを改善

---

pages/tickets/index.vue

自分が取得した整理券の一覧画面のデザインを大幅に改訂．
- 自分の整理券を確認しやすいようにするため．
- 各クラスの受付担当者が簡単に整理券を確認できるようにするため．
- 説明文章を平易に改訂．
- UIをシンプルなものに変更．
- 開場されているかどうかを「開場前」「開場中」「公演終了」の3種類に分けて表示．
- 開場中の整理券がある場合は最上部に大きく表示される
1. 開場中の整理券がある場合は最上部に大きく表示される
2. 「あなたの整理券」
3. 入場していない場合（もうちょっと可愛くしたい）
4. 整理券を取得していない場合

/tickets/ 持ってる整理券一覧のデザイン改良

---

pages/groups/index.vue

- タイトル，団体名，説明文が，横幅に寄らず一行に収まるように変更．
- [えいすけの指摘](https://github.com/hibiya-itchief/quaint-app/pull/249#discussion_r1284456347)を元にlg="3"に変更

fix: /groupsのタイトル・説明文を1行に収める 

---

nuxt.config.ts
pages/groups/_groupId/index.vue
pages/groups/index.vue

og:imageだけでは不十分で
twitter:image とする必要があった

fix: twitterでogpカードに画像が読み込まれない問題を修正

---

layouts/default.vue

表題の通り
表題のボタンを押すと青い状態が残り続けるが、
adminページを開いている状態を意味しているかのように受け取れるのであえて放置。
(あと、直し方がわからない)

adminページのリンクをログアウトボタンの左に

---

pages/tickets/index.vue
types/quaint.ts

表題の通り．
- https://github.com/hibiya-itchief/quaint-api/pull/119
の変更にフロントエンドを対応させた．
- キャンセル済みのチケットを同一ページから見られるようにしたい．
- イメージは，タブで「有効な整理券」「キャンセル済み」を選択できる．
以下のバッジ：
- 「開場前」（開場20分前まで）
- 「開場中」（開場20分前~公演終了時刻）
- 「公演終了」（公演終了時刻~）
は時間で管理してる，当日の公演スケジュール変更に対応できるよう，APIと連動させて柔軟に対応させたい（設計は未検討）．

Ticket.statusに対応 in tickets

---

pages/login.vue

* #334 
２行に分ける際にテキスト部分の縦の長さがそのまま２倍になったので、ボタンの縦の長さもそのまま２倍にして比率を保ちました
px数で比例式立ててもちゃんと同じ比率になりました

/login ログインボタンを外にはみ出さないように

---

pages/groups/_groupId/index.vue

* #355 
とりあえず暫定的に、Hebe、外部団体、部活動、のいずれかのタグを持っていると観劇予約パネルが表示されなくなります
本当はクラス劇でないのならという条件にしたかったんですが、それだと開発環境が全部表示されなくなるので…

/_groupId 観劇予約パネル表示の暫定更新

---

nuxt.config.ts

これでnuxt generateしてみたら200.htmlが生成されないことを確認しました
cloudflareのプレビューで確かめるか、直近のリリースで試してほしいです

fix: add fallback, remove extendRoutes

---

layouts/default.vue

いいデザインが思いつかず。
スマホのスクショを。
このように白背景では擬態します
（枠線をつけなかったのは、ハンバーガーを押してメニューを出したときに枠線を消す処理を実装するほど枠線は大事ではないと判断したから）

fix: add hamburger-menu background

---

pages/groups/_groupId/index.vue
pages/groups/index.vue

* #193 
* #237 
* #357 
結局、/groupsから追加する機能を実装するのはかなり骨折り事業であることがわかり、
アイコンだけに留めました
結構変更箇所が多いので念入りなreviewをおねがいします
デザインが好きという理由が導入の原動力
タグと違いいつでもブックマーク絞り込みが可能

/groupsお気に入り(ブックマーク)機能の調整

---

nuxt.config.ts

nuxtconfigの色一覧、もともとdarkだったものを無理やり全部lightに魔改造したため
dark仕様の色をlightで使っていました
プレビュー試してません

祭徠以外の色を無効に

---

pages/groups/_groupId/index.vue

(サマーウォーズ)
実際は最大１つか２つが同時に配布中になりえる、はず

/_groupId 公演を始まる順で表示

---

pages/groups/_groupId/edit/index.vue

* 団体ID(ページのURL)をハイパーリンクに
* Hebe等では公演を編集するメニューが出ないように
* 団体削除dialogのサイズを調整
団体削除ボタンはすでにAdmin以外表示されないようになってました

/edit リンクに飛べるように、Hebe等では公演を編集できないように

---

pages/groups/_groupId/index.vue

containを追加
現行では、スマホ表示は割とcontainなくても大丈夫なんですけど、PCで、特に15R,26Rなんかはcontainないと厳しい表示になってます

fix: add contain in /_groupId

---

pages/groups/_groupId/data/index.vue
pages/groups/_groupId/edit/index.vue
pages/groups/_groupId/index.vue

test13rにて、時系列学校(target: school)1→学校2となるように学校及び紙(target: paper)を用意
コード的には正しいソート順になったはずだが、実際に動かすとたまに2→2→1→1になることがある
開発環境特有のバグの可能性がある
オンライン→紙という順番、配布中→配布時間外という順番、の２原則はずっと正しいまま。

/data 正しいソート順に など

---

pages/groups/_groupId/data/index.vue
pages/groups/_groupId/index.vue

・createdのlist〇〇機構をasyncDataに移動
(これによって$nuxt.refreshで更新するように）
・「残りわずか」の文字サイズをちょっと小さくしてスマホでも表示が崩れにくいように
・あとAPIでticketsキャッシュしないようにすれば完全に整理券取得競争が行えるように
（ただし、そうすると配布開始の時にたくさんの人が/ticketsを連打することになるから、まさに負荷がどうなるか…）

/_groupId 再読み込みでちゃんと再読み込みされるように

---

components/CountDown.vue
pages/groups/_groupId/index.vue

一旦、映像配信を非表示に。
そういえば、バージョン番号の一番下のことをパッチバージョンと呼ぶらしく、ほんとは新規機能追加をマイナーバージョンで統一すべきだったんですかね…
まあ'23は正直新しい機能ずくめでしたのでしょうがないといえばしょうがない

Release 1.0.5 のパッチ

---

.github/workflows/ci.yml

ログインしているかどうかをチェックする表示が正しく表示されるように。
というのは建前で、実際は現在ちゃんとビルドが行われているか確認するためのRelease。
ビルドが行われていないことに由来するのではないかと思われるバグが報告されているため。

Release 1.0.8

---

pages/groups/_groupId/index.vue

リンクの表示をビルドに依存しないように
これで勝山のリンクが永遠に表示されない現象が治ってほしい

fix: linkを適宜調達するように 暫定

---

.github/workflows/ci.yml

Nodeのバージョンを落としても治らなかった勝山のリンクが表示されないバグの修正、力業
成功したらうれしい

Release 1.0.9
