hibiya-itchief/quaint-app

- axiossetting.js
- layouts/default.vue
- mixins/utilities.js
- nuxt.config.js
- package.json
- pages/groups/index.vue
- pages/index.vue
- pages/signin.vue
- pages/tickets/index.vue
- yarn.lock
login,logout後のredirectがうまくいってなかったが、(vuexの)storeフォルダにindex.jsを作ることで解決
v-row,v-col,v-sheetを使ってとりあえずデザインを整えた
これからはデフォルトで認証が必要になる。認証がいらないページを作るときはauth:falseを指定すればよい
> @nuxt/auth-nextのmiddlewareを使って認証機能を実装。

- pages/tickets/index.vue
・データは適当に入れたので適宜修正が必要です。よろしくお願いします。
> 整理券一覧ページを作った

- nuxt.config.js
- package.json
- pages/tickets/index.vue
- yarn.lock
> 自分の持っている整理券を表示する

- nuxt.config.js
- pages/groups/_groupId/edit/index.vue
- pages/groups/_groupId/index.vue
- pages/groups/index.vue
> 60 groupの各個別ページの更新

- env.development.js
- env.production.js
- env.staging.js
- layouts/default.vue
- nuxt.config.js
- package.json
- pages/callback.vue
- pages/index.vue
- pages/login.vue
- patches/@nuxtjs+auth-next+5.0.0-1667386184.dfbbb54.patch
- tsconfig.json
- yarn.lock
Azure AD, Azure AD B2Cを利用したログインを実装した。
一般客・保護者はB2Cで、校内の人はADで
issue: #95 
昨年は、ログインの際にもDBアクセスしていたため、同時に多数のログインがあると落ちてしまっていた。ログイン処理をIDaaSに任せることで負荷を軽減する。
> feat: Login with Azure AD and B2C

- pages/spectest.vue
> spectest.vue を更新

- pages/callback.vue
- pages/login.vue
callbackのerror検知&loginに飛ばす+エラー文
> Kakihara kendama

- pages/spectest.vue
テスト5・6を追加
1人の端末から20人分、50人分のリクエストをおくる
- 現状1番負荷が大きい「1人の端末から10人分リクエスト送る」だとたぶん鯖落ちしなさそう(サーバーの限界を知るという目的が達せられなそう)なのと、
- 一般客が使用した場合の負荷についてより説得力を持たせるため
- 時間の制約
- 今から原稿変えて大丈夫か
> もっと負荷をかけるテストを作成

- pages/groups/_groupId/index.vue
- pages/groups/index.vue
resolveするのがめんどくさそうだったので新しくbranchつくってやりました
( 11r, 11r )だったのが( seiryofes.groups.favorite.11r, 11r)になりました
> 133 お気に入り機能リベンジ

- env.development.js
- env.production.js
- env.staging.js
- layouts/default.vue
> merge develop into main

- env.development.js
- env.production.js
- env.staging.js
- pages/groups/_groupId/index.vue
- pages/groups/index.vue
存在する公演が0426spectestと11rしかない？ため
その２公演でのみ正しく動作していることを確認しました
また例により競合してしまうため１回branchをつくってぷるりくします
↑まったく同じ内容であれば自分でまーじしてもいいですか？
> #134 信号機解体

- pages/groups/_groupId/index.vue
> fix: #177 1および3のバグを修正

- pages/tickets/index.vue
> #177 fix ticketpage

- pages/groups/index.vue
> ぷるりく#190.5 お気に入り機能修正

- pages/groups/_groupId/index.vue
今まで、灰色マークで配布時間外だと示されていても、
クリックしたらdialogが出ていました、おそらく
なので、おしたらエラーのsnackbarを出すようにしました
ご査収ください
> 配布時間外の公演を選択した時の動作

- pages/groups/_groupId/edit/index.vue
- pages/groups/_groupId/index.vue
> 190 editpage

- pages/groups/_groupId/edit/index.vue
表題の通りです
途中で作業を中断して集中力も落ちていたことが多かったので、
reviewしていただけると。
<v-text-field ~~~ value="hoge">のエラー（lineのやつです）は、
調べる限り、v-model="add_event"のadd_eventが担っていたので消しました
> 公演削除の確認dialog及び団体削除ボタンのv-icon化

- layouts/default.vue
> #212-アカウントのowner表示

- .github/workflows/cloudflare-deploy-main.yml
- pages/admin/index.vue
GitHub Actionの動作を確かめるにはmainにマージしないといけない
> feat: 毎日ビルドのGitHub Actions /adminから手動

- layouts/default.vue
そういえばAdmin以外SwaggerUI使うことないのでAPIトークンの表示はAdminだけでいいんじゃないか？という思い付きです
codespace死んでしまっているので、エラーが出ていないか、lintエラーが出ないか、その2点確認おねがいします
> Admin以外にAPIトークンを見せない

- .devcontainer/devcontainer.json
(yarnとyarn installは同じ)
自分のcodespaceではそのままyarn run ~~~が行えるようになった。
誰か自分のcodespaceでもできているか試していただきたいです。
> yarn install自動で実行するように

- pages/groups/index.vue
> /groupsの検索の大文字小文字を寛容化

- pages/groups/_groupId/index.vue
- pages/groups/index.vue
>  /groupsの絞り込みタグをページ変遷後も維持

- pages/groups/index.vue
とりあえずid順・昇順で固定した仮実装。
methodsのみの実装となる。
> /groups ソート機能の仮実装(id,昇順)

- pages/tickets/index.vue
- types/quaint.ts
Reverts hibiya-itchief/quaint-app#302
ticket.status はapi-devの方には適用されているが、バグが潜んでいる可能性があるため本番環境のAPIには適用待ちなので、revert
> Revert "Ticket.statusに対応 in tickets"

- pages/tickets/index.vue
> /tickets 「公演を探す」に変更

- pages/tickets/index.vue
表題の通り．
- https://github.com/hibiya-itchief/quaint-api/pull/119
の変更にフロントエンドを対応させた．
> Ticket.statusに対応 in tickets （2回目）

- pages/groups/_groupId/index.vue
- pages/tickets/index.vue
* #268 
整理券を取得しました！「整理券」タブから～～～
の「整理券」タブをハイパーリンクにした。
ただし緑背景に青色の文字だからなのか違和感がすごい
とりあえずデフォルトの色で提出。
また、/ticketsのsnackbarにバツを追加。
> #268 /groupIdのsnackbarから/ticketsに飛ばす

- pages/groups/index.vue
> #234 & #283 タグ機能とソート機能を合体

- pages/login.vue
The disabling of the general login button was stopped at Spectest, so it was hastily made available to Develop as well.
> Disabled login btn

- nuxt.config.ts
- pages/groups/index.vue
/groups デフォルト順のソートはnuxt generateでするようにした
- #331 
@hibiyahibiyahibiya 作った人が一番わかると思うのでレビューお願いします
> /groups デフォルト順のソートはnuxt generateで

- pages/groups/_groupId/index.vue
> fix: 学校アカウント以外は人数選択できるように

- pages/groups/index.vue
* #335 
https://github.com/hibiya-itchief/quaint-app/blob/e5e07e461058e277eb341f27b004741abbe88a25/layouts/default.vue#L304
これをパクっただけ
> /groups 矢印が回転するように

- pages/groups/_groupId/index.vue
* #256 
* #347 
※「残りわずか」は本来オレンジ
> /_groupId 細かいデザインの調整

- pages/admin/index.vue
- pages/admin/manage_owner.vue
- types/quaint.ts
> /admin ちょっと使いやすく

- layouts/default.vue
> アカウントの属性を正しく表示するように

- nuxt.config.ts
- pages/index.vue
> 405-祭徠と検索してもヒットするようにする

- layouts/error.vue
- pages/404.vue
- pages/admin/index.vue
- pages/admin/manage_owner.vue
- pages/callback.vue
- pages/groups/_groupId/edit/index.vue
* #368
* #380 
* #381 
0.5.0実装時、/aaaと/groups/aaaの表示がどうなっているかをみてからreviewでお願いします
いまnuxt generate
試したらどっちも404ページ出せたんですけど…
> 404ページなどの調整

- pages/about.vue
- pages/access.vue
- pages/help.vue
- pages/index.vue
- pages/map.vue
- pages/schedule.vue
- pages/system.vue
現状
何か提案等あれば。
あと、「祭徠」にふりがなつけるつもりです
> トップページの手直し

- pages/groups/_groupId/data/index.vue
- pages/groups/_groupId/edit/index.vue
- pages/groups/_groupId/index.vue
> #340 クラ代紙整理券確認できるページ

- pages/groups/_groupId/edit/index.vue
> /edit targetを今年仕様に更新

- pages/groups/_groupId/data/index.vue
- pages/groups/_groupId/index.vue
> 万人に/dataが表示されている不具合を修正

- pages/groups/_groupId/edit/index.vue
- pages/groups/_groupId/index.vue
> #449 しぶとく残るIT部隊

- pages/spectest2.vue
懐かしいですね
ただし、spectestというエンドポイントは今ないと思いますので、このままでは動きません
urlは　localhost:3000/spectest2　です
> 負荷テスト復活 for 9/12

- pages/groups/_groupId/data/index.vue
- pages/groups/_groupId/index.vue
> fix: 公演一覧ソート add new Date

- pages/tickets/index.vue
> /tickets 「開場中」時、公演名も表示されるように

- pages/groups/_groupId/edit/index.vue
- pages/groups/_groupId/index.vue
- types/quaint.ts
> Release 1.0.2

- pages/groups/_groupId/index.vue
> Release 1.0.5

- components/CountDown.vue
> feat: conponentの日付を変更

- pages/groups/_groupId/index.vue
日付を'24までに変更
いきなりバージョン更新の価値が暴落してますね…
> Release 1.0.6

- pages/groups/_groupId/index.vue
> feat: 一時的に映像配信を非表示

- pages/groups/index.vue
> #386 調整 (ブックマーク)

- pages/groups/_groupId/index.vue
> Revert #504（Release 1.0.7と為す）

- layouts/default.vue
ログインしていないのにログインしているかのように表示されることがあった記憶。
> fix: ログイン中の表示もclient only

- pages/groups/_groupId/index.vue
> LinksをAsyncDataを用いてビルド時に生成

- .github/workflows/ci.yml
> リンクをビルド時に取得するように

- .github/workflows/cloudflare-deploy-main.yml
github actionで毎日cloudflareにデプロイされるのを停止
> 毎日デプロイするのを停止

- .github/workflows/cloudflare-deploy-main.yml
- pages/groups/_groupId/index.vue
cloudflareに毎日デプロイするgithub actionsを停止
> 毎日cloudflareにデプロイするのを停止

- .github/workflows/ci.yml
> APIからの切り離し

- pages/groups/_groupId/index.vue
> 整理券を取得できないように変更
